spring:
  application:
    name: gladskoy-middle-service
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

server:
  port: 8081

backend:
  service:
    url: http://localhost:8082
  accounts:
    - name: "Акционный"
      description: "Для новых пользователей. При регистрации начисляется 5000 руб."
      init-amount: 5000
      type: promo
    - name: "Депозитный"
      description: "Основной депозитный счёт. При открытии на счету будет нулевой баланс."
      type: common

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %clr(%5level) [%15.15t] %clr(%-45.55logger{39}){cyan} : %m%n%wEx"
  level:
    ru.gpbitfactory.minibank.middle:
      createclient:
        service: info
        restclient: debug
      createaccount:
        service: info
        restclient: debug