spring:
  application:
    name: gladskoy-middle-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %clr(%5level) [%15.15t] %clr(%-45.55logger{39}){cyan} : %m%n%wEx"
  level:
    ru.gpbitfactory.minibank.middle:
      controller: info
      service: info